{
 "title": "Geth System Resources",
 "tags": [
  "eth1.0",
  "ethereum",
  "geth"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(vflux_server_active_count{}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(vflux_server_active_count{}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transaction Rate (tx/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(txpool_known{namespace=\"$namespace\",pod=\"$pod\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pending Transactions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "txpool_pending{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Geth Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_memory_used" }
   ]
  },
  {
   "title": "Geth CPU Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_threads" }
   ]
  },
  {
   "title": "Last Received Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_receipt{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total System Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "Geth Processor Loading",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "system_cpu_procload" }
   ]
  },
  {
   "title": "Peer Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_peers{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Traffic (bytes/s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(p2p_egress{namespace=\"$namespace\",pod=\"$pod\"}[5m])",
     "legendFormat": "Out: {{pod}}"
    },
    {
     "expr": "rate(p2p_ingress{namespace=\"$namespace\",pod=\"$pod\"}[5m])",
     "legendFormat": "In: {{pod}}"
    }
   ]
  },
  {
   "title": "Disk Activity (bytes/s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(system_disk_readbytes{namespace=\"$namespace\",pod=\"$pod\"}[5m])",
     "legendFormat": "Read: {{pod}}"
    },
    {
     "expr": "rate(system_disk_writebytes{namespace=\"$namespace\",pod=\"$pod\"}[5m])",
     "legendFormat": "Write: {{pod}}"
    }
   ]
  },
  {
   "title": "Chain Data Disk Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_size{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RPC Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpc_requests{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Write Activity (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(system_disk_writebytes{namespace=\"$namespace\",pod=\"$pod\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Read Activity (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(system_disk_readbytes{namespace=\"$namespace\",pod=\"$pod\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Outgoing Network (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(p2p_egress{namespace=\"$namespace\",pod=\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}